---
require:
  - cookstyle/chefstyle

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - "**/*.rb"
  Exclude:
    - "vendor/**/*"
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Naming/FileName:
  Exclude:
    - lib/kitchen-cinc-auditor.rb

Style/FormatStringToken:
  Exclude:
    - spec/**/*.rb
